source 'https://rubygems.org'

group :frontend do
  gem 'compass',        '<= 0.12.7'
  # Build compass sprites faster with oily_png.
  gem 'oily_png',       '~> 1.1'
  gem 'sass',           '<= 3.2.19'
  gem 'zen-grids', '1.4'
end
